CREATE TABLE DCFL_WEEKLY_CLASSIFICATION (
  CASHFLOW_NAME varchar(50) NOT NULL COMMENT '现金流类型',
  WEEKLY_NAME varchar(50) NOT NULL COMMENT '周报类型',
  CREATED_BY int(10) DEFAULT NULL,
  CREATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY int(10) DEFAULT NULL,
  UPDATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='周报统计分类标准';


SELECT A.CASHFLOW_NAME,
       SUM(A.WRITE_OFF_DUE_AMOUNT) AS WRITE_OFF_DUE_AMOUNT,
	   SUM(A.WRITE_OFF_PRINCIPAL) AS WRITE_OFF_PRINCIPAL,
	   SUM(A.WRITE_OFF_INTEREST) AS WRITE_OFF_INTEREST
FROM WRITE_OFF_INFO A
GROUP BY A.CASHFLOW_NAME
ORDER BY A.CASHFLOW_NAME;