CREATE TABLE ELE_INVOICE_INFO (
ELE_INVOICE_ID int(20) NOT NULL AUTO_INCREMENT COMMENT '电子发票ID/PK',
INVOICE_ID int(20) NOT NULL COMMENT '发票表ID',
DOCUMENT_TYPE varchar(30) NULL COMMENT '单据类型',
DOCUMENT_CATEGORY varchar(30) NULL COMMENT '单据类别',
SERIAL_NUM varchar(20) NOT NULL COMMENT '流水号', --SWNO
SALE_TAX varchar(50) DEFAULT '' COMMENT '销方税号',
CUST_NAME varchar(100) DEFAULT '' COMMENT '购方名称',
CUST_TAX_NO varchar(100) NULL COMMENT '购方税号',
CUST_ADDR varchar(200) NULL COMMENT '购方地址',
CUST_TELEPHONE varchar(100) NOT NULL COMMENT '购货方手机号',
CUST_PHONE varchar(100) NULL COMMENT '购方固定电话',
CUST_EMAIL varchar(200) NULL COMMENT '购方邮箱',
CUST_BANK_ACCOUNT varchar(200) NULL COMMENT '开户行+账号',
CUST_TYPE varchar(200) NULL COMMENT '购货方企业类型',
ELE_INVOICE_MEMO varchar(200) NULL COMMENT '备注',--INVO_MEMO
ELE_INVOICE_TYPE varchar(5) NOT NULL COMMENT '发票类型',--INV_TYPE
CANCEL_NUM varchar(20) NULL COMMENT '退货单号',--THDH
BILL_TYPE varchar(5) NOT NULL COMMENT '开票类型',
SPECIAL_RED_FLAG varchar(5) NOT NULL COMMENT '特殊红冲标志',
OPERATION_CODE varchar(5) NOT NULL COMMENT '操作代码',
ACCOUNT_PAYEE varchar(20) NULL COMMENT '收款员', --SKY
ACCOUNT_TIME timestamp NULL COMMENT '记账日期',   --ACCOUNTING_DATE
ISSUER int(10) NULL COMMENT '开票人',   --KPY
ISSUED_TIME timestamp NULL COMMENT '开票日期',
REVIEWER int(10) NULL COMMENT '复核人',   --FHR
REVIEWED_TIME timestamp NULL COMMENT '复核日期',
FORMER_INVOICE_CODE varchar(20) NULL COMMENT '原发票代码',--YFPDM
FORMER_INVOICE_NUM varchar(20) NULL COMMENT '原发票号码',--YFPHM
ELE_INVOICE_STATUS_CODE varchar(20) NULL COMMENT '电子发票状态CODE',--STATUS
ELE_INVOICE_STATUS_NAME varchar(20) NULL COMMENT '电子发票状态NAME',
PDF_URL varchar(2000) NULL COMMENT '电子接口返回的pdf附件URL',
INVOICE_DATE timestamp NULL COMMENT '发票日期（金税可回传）',
INVOICE_NUMBER varchar(20) NULL COMMENT '发票号（金税可回传）',
INVOICE_CODE varchar(20) NULL COMMENT '发票代码（金税可回传）',  --ACR_INVOICE_HD.VAT_INVOICE_CODE
INVOICE_INTERFACE_STATUS_CODE varchar(20) NULL COMMENT '金税接口状态CODE（PENDING / TRANSFERED / BACK）',  --ACR_INVOICE_HD.VAT_INTERFACE_STATUS
INVOICE_INTERFACE_STATUS_NAME varchar(20) NULL COMMENT '金税接口状态NAME（PENDING-暂挂 / TRANSFERED-已传金税 / BACK-金税已回写）',
INVOICE_INTERFACE_TAX_CODE varchar(20) NULL COMMENT '金税返回code',  --ACR_INVOICE_HD.TAX_CODE
INVOICE_INTERFACE_TAX_MESSAGE varchar(20) NULL COMMENT '金税返回message',  --ACR_INVOICE_HD.TAX_MSG
INVOICE_CANCEL_FLAG varchar(2) NULL COMMENT '发票取消标志 取消不通过金税，取消后返回到发票创建',  --ACR_INVOICE_HD.CANCEL_FLAG
INVOICE_CANCEL_DESC varchar(200) NULL COMMENT '发票取消说明',  --ACR_INVOICE_HD.CANCLE_DESC
INVOICE_CANCEL_DATE timestamp NULL COMMENT '发票取消日期',
INVOICE_INVALID_FLAG varchar(2) NULL COMMENT '发票作废标志 通过金税，暂时只有纸票行为',  --ACR_INVOICE_HD.INVALID_FLAG
INVOICE_INVALID_DESC varchar(200) NULL COMMENT '发票作废说明',  --ACR_INVOICE_HD.INVALID_DESC
INVOICE_INVALID_CODE varchar(20) NULL COMMENT '发票作废CODE',
INVOICE_INVALID_NAME varchar(20) NULL COMMENT '发票作废NAME',
INVOICE_INTERFACE_INVALID_CODE varchar(20) NULL COMMENT '金税返回作废code',  --ACR_INVOICE_HD.CANCLE_RETURN_CODE
INVOICE_INTERFACE_INVALID_MESSAGE varchar(200) NULL COMMENT '金税返回作废message',  --ACR_INVOICE_HD.CANCLE_RETURN_MESSAGE
INVOICE_INVALID_DATE timestamp NULL COMMENT '发票作废日期',
INVOICE_REVERSE_FLAG varchar(2) NULL COMMENT '发票反冲标志 通过金税，纸票的普票不能跨月，纸票的专票可以跨月；电票的普票和专票都可以跨月 ',  --REVERSED_FLAG
INVOICE_REVERSE_DESC varchar(200) NULL COMMENT '发票反冲说明',  --ACR_INVOICE_HD.REVERSE_DESC / CHYY
INVOICE_REVERSE_CODE varchar(20) NULL COMMENT '发票反冲CODE N/未反冲 ，W/被反冲，R/反冲',
INVOICE_REVERSE_NAME varchar(20) NULL COMMENT '发票反冲NAME',
INVOICE_INTERFACE_REVERSE_CODE varchar(20) NULL COMMENT '金税返回反冲code',  --ACR_INVOICE_HD.CANCLE_RETURN_CODE
INVOICE_INTERFACE_REVERSE_MESSAGE varchar(200) NULL COMMENT '金税返回反冲message',  --ACR_INVOICE_HD.CANCLE_RETURN_MESSAGE
INVOICE_RED_NOTICE_NUM varchar(20) NULL COMMENT '专用发票红票通知单号',  --ACR_INVOICE_HD.VAT_RED_NOTICE_NUM
INVOICE_REVERSE_DATE timestamp NULL COMMENT '发票反冲日期',
CREATED_BY int(10) NULL COMMENT '创建人',
CREATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
UPDATED_BY int(10) NULL COMMENT '更新人',
UPDATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY (`ELE_INVOICE_ID`)
)ENGINE=InnoDB AUTO_INCREMENT=10783 DEFAULT CHARSET=utf8 COMMENT='电子发票表';



/*
Navicat MySQL Data Transfer

Source Server         : 10.40.59.129
Source Server Version : 80018
Source Host           : 10.40.59.129:3306
Source Database       : tax

Target Server Type    : MYSQL
Target Server Version : 80018
File Encoding         : 65001

Date: 2020-03-18 15:16:52
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for ELE_INVOICE_INFO
-- ----------------------------
DROP TABLE IF EXISTS `ELE_INVOICE_INFO`;
CREATE TABLE `ELE_INVOICE_INFO` (
  `ELE_INVOICE_ID` int(20) NOT NULL AUTO_INCREMENT COMMENT '电子发票ID/PK',
  `INVOICE_ID` int(20) NOT NULL COMMENT '发票表ID',
  `DOCUMENT_TYPE` varchar(30) DEFAULT NULL COMMENT '单据类型',
  `DOCUMENT_CATEGORY` varchar(30) DEFAULT NULL COMMENT '单据类别',
  `SERIAL_NUM` varchar(20) NOT NULL COMMENT '流水号',
  `SALE_TAX` varchar(50) DEFAULT '' COMMENT '销方税号',
  `CUST_NAME` varchar(100) DEFAULT '' COMMENT '购方名称',
  `CUST_TAX_NO` varchar(100) DEFAULT NULL COMMENT '购方税号',
  `CUST_ADDR` varchar(200) DEFAULT NULL COMMENT '购方地址',
  `CUST_TELEPHONE` varchar(100) NOT NULL COMMENT '购货方手机号',
  `CUST_PHONE` varchar(100) DEFAULT NULL COMMENT '购方固定电话',
  `CUST_EMAIL` varchar(200) DEFAULT NULL COMMENT '购方邮箱',
  `CUST_BANK_ACCOUNT` varchar(200) DEFAULT NULL COMMENT '开户行+账号',
  `CUST_TYPE` varchar(200) DEFAULT NULL COMMENT '购货方企业类型',
  `ELE_INVOICE_MEMO` varchar(200) DEFAULT NULL COMMENT '备注',
  `ELE_INVOICE_TYPE` varchar(5) NOT NULL COMMENT '发票类型',
  `CANCEL_NUM` varchar(20) DEFAULT NULL COMMENT '退货单号',
  `BILL_TYPE` varchar(5) NOT NULL COMMENT '开票类型',
  `SPECIAL_RED_FLAG` varchar(5) NOT NULL COMMENT '特殊红冲标志',
  `OPERATION_CODE` varchar(5) NOT NULL COMMENT '操作代码',
  `ACCOUNT_PAYEE` varchar(20) DEFAULT NULL COMMENT '收款员',
  `ACCOUNT_TIME` timestamp NULL DEFAULT NULL COMMENT '记账日期',
  `ISSUER` int(10) DEFAULT NULL COMMENT '开票人',
  `ISSUED_TIME` timestamp NULL DEFAULT NULL COMMENT '开票日期',
  `REVIEWER` int(10) DEFAULT NULL COMMENT '复核人',
  `REVIEWED_TIME` timestamp NULL DEFAULT NULL COMMENT '复核日期',
  `FORMER_INVOICE_CODE` varchar(20) DEFAULT NULL COMMENT '原发票代码',
  `FORMER_INVOICE_NUM` varchar(20) DEFAULT NULL COMMENT '原发票号码',
  `ELE_INVOICE_STATUS_CODE` varchar(20) DEFAULT NULL COMMENT '电子发票状态CODE',
  `ELE_INVOICE_STATUS_NAME` varchar(20) DEFAULT NULL COMMENT '电子发票状态NAME',
  `PDF_URL` varchar(2000) DEFAULT NULL COMMENT '电子接口返回的pdf附件URL',
  `INVOICE_DATE` timestamp NULL DEFAULT NULL COMMENT '发票日期（金税可回传）',
  `INVOICE_NUMBER` varchar(20) DEFAULT NULL COMMENT '发票号（金税可回传）',
  `INVOICE_CODE` varchar(20) DEFAULT NULL COMMENT '发票代码（金税可回传）',
  `INVOICE_INTERFACE_STATUS_CODE` varchar(20) DEFAULT NULL COMMENT '金税接口状态CODE（PENDING / TRANSFERED / BACK）',
  `INVOICE_INTERFACE_STATUS_NAME` varchar(20) DEFAULT NULL COMMENT '金税接口状态NAME（PENDING-暂挂 / TRANSFERED-已传金税 / BACK-金税已回写）',
  `INVOICE_INTERFACE_TAX_CODE` varchar(20) DEFAULT NULL COMMENT '金税返回code',
  `INVOICE_INTERFACE_TAX_MESSAGE` varchar(20) DEFAULT NULL COMMENT '金税返回message',
  `INVOICE_CANCEL_FLAG` varchar(2) DEFAULT NULL COMMENT '发票取消标志 取消不通过金税，取消后返回到发票创建',
  `INVOICE_CANCEL_DESC` varchar(200) DEFAULT NULL COMMENT '发票取消说明',
  `INVOICE_CANCEL_DATE` timestamp NULL DEFAULT NULL COMMENT '发票取消日期',
  `INVOICE_INVALID_FLAG` varchar(2) DEFAULT NULL COMMENT '发票作废标志 通过金税，暂时只有纸票行为',
  `INVOICE_INVALID_DESC` varchar(200) DEFAULT NULL COMMENT '发票作废说明',
  `INVOICE_INVALID_CODE` varchar(20) DEFAULT NULL COMMENT '发票作废CODE',
  `INVOICE_INVALID_NAME` varchar(20) DEFAULT NULL COMMENT '发票作废NAME',
  `INVOICE_INTERFACE_INVALID_CODE` varchar(20) DEFAULT NULL COMMENT '金税返回作废code',
  `INVOICE_INTERFACE_INVALID_MESSAGE` varchar(200) DEFAULT NULL COMMENT '金税返回作废message',
  `INVOICE_INVALID_DATE` timestamp NULL DEFAULT NULL COMMENT '发票作废日期',
  `INVOICE_REVERSE_FLAG` varchar(2) DEFAULT NULL COMMENT '发票反冲标志 通过金税，纸票的普票不能跨月，纸票的专票可以跨月；电票的普票和专票都可以跨月 ',
  `INVOICE_REVERSE_DESC` varchar(200) DEFAULT NULL COMMENT '发票反冲说明',
  `INVOICE_REVERSE_CODE` varchar(20) DEFAULT NULL COMMENT '发票反冲CODE N/未反冲 ，W/被反冲，R/反冲',
  `INVOICE_REVERSE_NAME` varchar(20) DEFAULT NULL COMMENT '发票反冲NAME',
  `INVOICE_INTERFACE_REVERSE_CODE` varchar(20) DEFAULT NULL COMMENT '金税返回反冲code',
  `INVOICE_INTERFACE_REVERSE_MESSAGE` varchar(200) DEFAULT NULL COMMENT '金税返回反冲message',
  `INVOICE_RED_NOTICE_NUM` varchar(20) DEFAULT NULL COMMENT '专用发票红票通知单号',
  `INVOICE_REVERSE_DATE` timestamp NULL DEFAULT NULL COMMENT '发票反冲日期',
  `CREATED_BY` int(10) DEFAULT NULL COMMENT '创建人',
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_BY` int(10) DEFAULT NULL COMMENT '更新人',
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ELE_INVOICE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10783 DEFAULT CHARSET=utf8 COMMENT='电子发票表';
