CREATE TABLE FY_ATTACHMENT_INFO (
  RECORD_ID int(20) NOT NULL AUTO_INCREMENT,
  TABLE_NAME varchar(30) DEFAULT '' COMMENT '表名',
  TABLE_PK_VALUE int(20) COMMENT '表主键',
  ATTACHMENT_ID int(20) COMMENT '附件id',
  CREATED_BY int(10) DEFAULT NULL,
  CREATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UPDATED_BY int(10) DEFAULT NULL,
  UPDATE_TIME timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`RECORD_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10783 DEFAULT CHARSET=utf8 COMMENT='附件表（关联表名）';