CREATE TABLE `INVOICE_TAX_CLASSIFICATION_CODE_TEMP` (
  `CLASS_ID` int(20) NOT NULL ,
  `CONTRACT_TYPE` varchar(25) DEFAULT '' COMMENT '合同类型',
  `CONTRACT_TYPE_N` varchar(25) DEFAULT '' ,
  `DIVISION` varchar(25) DEFAULT '' COMMENT '设备名称',
  `DIVISION_N` varchar(25) DEFAULT '' ,
  `CF_ITEM` varchar(25) DEFAULT '' COMMENT '现金流项目',
  `CF_ITEM_N` varchar(25) DEFAULT '',
  `CF_TYPE` varchar(25) DEFAULT '' COMMENT '现金流类型',
  `CF_TYPE_N` varchar(25) DEFAULT '' ,
  `TAX_CLASS_NUM` varchar(25) DEFAULT '' COMMENT '税收分类编码',
	`GOODS_VERSION` varchar(25) DEFAULT '' COMMENT '版本',
  `CREATED_BY` int(10) DEFAULT NULL,
  `CREATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATED_BY` int(10) DEFAULT NULL,
  `UPDATE_TIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`CLASS_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10783 DEFAULT CHARSET=utf8 COMMENT='税收分类编码临时表';